export const CHANGE_DATALIST = 'CHANGE_DATALIST';
export const REQUEST_LAUNCHYEAR_PENDING = 'REQUEST_LAUNCH_PENDING';
export const REQUEST_LAUNCHYEAR_SUCCESS = 'REQUEST_LAUNCH_SUCCESS';
export const REQUEST_LAUNCHYEAR_FAILED = 'REQUEST_LAUNCH_FAILED';
export const REQUEST_LAUNCHDATA_PENDING = 'REQUEST_LAUNCHDATA_PENDING';
export const REQUEST_LAUNCHDATA_SUCCESS = 'REQUEST_LAUNCHDATA_SUCCESS';
export const REQUEST_LAUNCHDATA_FAILED = 'REQUEST_LAUNCHDATA_FAILED';


